
import { Dress, DressType, Collection } from './types';

export const DRESSES: (Dress & { collection: Collection })[] = [
  {
    id: 'imperial-alma',
    name: 'Alma',
    description: 'Alma este o declarație de feminitate absolută, unde rafinamentul clasic întâlnește o delicatețe aproape onirică. Bustul, sculptat pe o structură invizibilă de corset, oferă un contur perfect, învăluit într-un strat de tulle fin ca o respirație. Aplicațiile de dantelă sunt dispuse organic, iar detaliile cusute manual vorbesc despre sute de ore de dedicație artizanală. Decolteul subtil și jocul de transparențe creează un echilibru perfect între senzualitate și poezie. Șiragul de nasturi din mătase de pe spate completează povestea, lăsând fusta amplă, din mătase naturală ivory, să curgă fluid și maiestuos la fiecare pas.',
    rentPrice: 5400,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Alma/IMG_5535.jpg',
    images: ['/images/Imperial/Alma/IMG_5535.jpg', '/images/Imperial/Alma/IMG_5536.jpg', '/images/Imperial/Alma/IMG_5537.jpg', '/images/Imperial/Alma/IMG_5545.jpg'],
    sketches: ['/images/alma_sketch_front_v3.png', '/images/alma_sketch_back.png', '/images/alma_sketch_movement.png'],
    currency: 'RON',
    sizes: ['54'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mătase naturală, Tulle fin, Dantelă', silhouette: 'A-Line / Fluidă', neckline: 'Decolteu subtil' }
  },
  {
    id: 'imperial-aurelia',
    name: 'Aurelia',
    description: 'Aurelia este definită de fluiditatea absolută a mătăsii naturale Ivory, o țesătură prețioasă care îmbrățișează silueta fără a o constrânge. Croită într-o linie fit & flare sofisticată, rochia se deschide grațios într-o trenă delicată ce transformă fiecare mișcare într-un dans. Decolteul în V profund este flancat de aplicații de dantelă fină, brodată manual, care coboară ca niște ramuri florale spre talie. Mânecile iluzie adaugă un contrast curajos între transparență și broderie, în timp ce șirul prelung de nasturi de pe spate onorează tradiția pură haute couture.',
    rentPrice: 3600,
    price: 4800,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Aurelia/IMG_5352.jpg',
    images: ['/images/Imperial/Aurelia/IMG_5352.jpg', '/images/Imperial/Aurelia/IMG_5353.jpg', '/images/Imperial/Aurelia/IMG_5357.jpg', '/images/Imperial/Aurelia/IMG_5549 (1).jpg'],
    sketches: ['/images/Imperial/Aurelia/aurelia_sketch.png'],
    currency: 'RON',
    sizes: ['38', '40'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mătase naturală, dantelă brodată manual, tul', silhouette: 'Fit & Flare', neckline: 'V-Neck cu inserție de tul' }
  },
  {
    id: 'imperial-argente',
    name: 'Argente',
    description: 'Argente pare desprinsă dintr-un vis parizian, purtat pe străzi pavate cu lumină caldă. Realizată din tafta albă imaculată cu irizații fine argintii, țesătura captează lumina într-un mod aproape diafan. Structura fermă a taftalei susține o fustă amplă, în linie A, formând un volum arhitectural spectaculos în mers. Contrastul dintre minimalismul curat al decolteului frontal și dramatismul seducător al spatelui decupat adânc în V este hipnotic. Cu mâneci lungi ornate cu un șirag nesfârșit de nasturi fini, Argente reprezintă echilibrul perfect între poezia vizuală și rigoarea croitoriei clasice.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Argente/argente_front.PNG',
    images: ['/images/Imperial/Argente/argente_front.PNG', '/images/Imperial/Argente/rgente_front_2.PNG', '/images/Imperial/Argente/argente_back..jpg', '/images/Imperial/Argente/argente_detail.jpg'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Alb cu irizații argintii'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tafta albă cu irizații, satin', silhouette: 'A-Line', neckline: 'Rotund / V-Shape pe spate' }
  },
  {
    id: 'imperial-daiana',
    name: 'Daiana',
    description: 'Aceasta rochie de mireasa este realizată din satin fin, mătăsos, extrem de plăcut la atingere, cu o suprafață netedă ce reflectă lumina delicat și elegant. Materialul are o cădere fluidă, urmărind linia corpului fără rigiditate și oferind confort la purtare si o structură rafinată. Croiala este feminină și minimalistă, cu un decolteu subtil în față, care conturează zona bustului într-un mod senzual, dar sofisticat. Talia este discret evidențiată, alungind vizual silueta, cu ajutorul franceurilor din partea superioara a fustei, cu linie dreaptă, care creează un efect elegant și aerisit. Mânecile lungi, ușor evazate, adaugă mișcare și lejeritate, completând armonios designul. Elementul central al rochiei este decolteul adânc în V pe spate, un detaliu seducător și rafinat, care pune în valoare linia spatelui fără a pierde din eleganță.',
    rentPrice: 3200,
    price: 4500,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Daiana/Daiana-front.jpg',
    images: ['/images/Imperial/Daiana/Daiana-front.jpg', '/images/Imperial/Daiana/Daiana-front3.jpg', '/images/Imperial/Daiana/Daina-front2.jpg', '/images/Imperial/Daiana/Daina-back1.jpg', '/images/Imperial/Daiana/Daiana-detail1.JPG', '/images/Imperial/Daiana/Daiana-detail2.JPG'],
    sketches: ['/images/Imperial/Daiana/daiana_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Satin fin, mătăsos', silhouette: 'Dreaptă / Minimalistă', neckline: 'Subtil rotunjit / V pe spate' }
  },
  {
    id: 'imperial-elia',
    name: 'Elia',
    description: 'Această rochie de mireasă tip sirenă, îmbină eleganța clasică cu senzualitatea modernă într-o siluetă perfect conturată. Partea de jos, realizată din mătase naturală, cade fluid și impecabil, urmărind linia corpului până la genunchi, unde se deschide delicat, oferind rochiei un mers grațios și o prezență spectaculoasă. Bustul este punctul central al creației: tip corset, cu transparențe fine, atent construite pentru a pune în valoare dantela aplicată manual. Jocul subtil dintre transparență și broderia bogată creează impresia de ușurință și rafinament. Un mare avantaj al acestei rochii este versatilitatea ei: se pretează excelent la accesorizare cu trene detașabile.',
    rentPrice: 3300,
    price: 4500,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Elia/IMG_5414.jpg',
    images: ['/images/Imperial/Elia/IMG_5414.jpg', '/images/Imperial/Elia/IMG_5415.jpg', '/images/Imperial/Elia/IMG_5552.jpg', '/images/Imperial/Elia/IMG_5553.jpg', '/images/Imperial/Elia/IMG_5554.jpg'],
    sketches: ['/images/Imperial/Elia/elia_sketch.png'],
    currency: 'RON',
    sizes: ['38'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mătase naturală, dantelă', silhouette: 'Sirenă', neckline: 'Corset Illusion' }
  },
  {
    id: 'elise-elise',
    name: 'Elise',
    description: 'Elise este o rochie de mireasă realizată din tafta perlată, cu o strălucire delicată și structură impecabilă, ce pune în valoare rafinamentul unei siluete clasice. Corsajul are un decolteu amplu, tip bardot, cu linii suprapuse ce conturează elegant zona umerilor și a bustului. Talia este bine definită, iar fusta amplă, cu volum bogat și trenă fluidă, cade armonios în pliuri ample, oferind un aer regal și sofisticat. Spatele rochiei este accentuat de un decolteu în V și de o fundă decorativă din același material, cu panglici lungi ce se prelungesc grațios peste trenă, adăugând un detaliu romantic și spectaculos. Aceasta conferă rochiei un aspect luxos, păstrând în același timp o eleganță atemporală. O rochie ideală pentru mireasa care își dorește un look clasic, nobil și memorabil.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/Elise/IMG_5405.jpg',
    images: ['/images/Elise/IMG_5405.jpg', '/images/Elise/IMG_5408.jpg', '/images/Elise/IMG_5556.jpg', '/images/Elise/IMG_5561.jpg', '/images/Elise/IMG_5563.jpg', '/images/Elise/IMG_5564.jpg'],
    sketches: ['/images/Elise/elise_sketch.png'],
    currency: 'RON',
    sizes: ['50'],
    colors: ['Ivory'],
    collection: Collection.ELISE,
    details: { fabric: 'Tafta perlată', silhouette: 'Prințesă / A-Line', neckline: 'Bardot / Suprapus' }
  },
  {
    id: 'imperial-ivory-grace',
    name: 'Ivory Grace',
    description: 'Această rochie de mireasă emană o eleganță liniștită, aproape diafană, fiind creată dintr-un satin de o noblețe rară, extrem de fin și mătăsos, plăcut la atingere precum o șoaptă. În zona decolteului, rochia dezvăluie sufletul ei prețios: o dantelă fină, cusută integral manual, bogat ornamentată cu mărgele delicate. Mânecile lungi adaugă un plus de distincție și grație, urmărind delicat linia brațelor. Talia este marcată subtil, iar fusta amplă se revarsă în pliuri moi, fluide, până la podea, prelungindu-se într-o trenă discretă, dar plină de noblețe. Spatele păstrează aceeași simplitate elegantă, lăsând croiala impecabilă și materialul prețios să vorbească în tăcere.',
    rentPrice: 3800,
    price: 6900,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Ivory Grace/IMG_5395.jpg',
    images: ['/images/Imperial/Ivory Grace/IMG_5395.jpg', '/images/Imperial/Ivory Grace/IMG_5399.jpg', '/images/Imperial/Ivory Grace/f202fbc6-6dd7-442b-8121-0cc159e5ff40.JPG'],
    sketches: ['/images/Imperial/Ivory Grace/ivory_grace_sketch.png'],
    currency: 'RON',
    sizes: ['38', '40'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Satin nobil, dantelă cu mărgele', silhouette: 'Dreaptă / A-Line', neckline: 'Dantelă aplicată manual' }
  },
  {
    id: 'imperial-lumiere',
    name: 'Lumiere',
    description: 'Aceasta rochie de mireasa este construită dintr-un un dialog subtil de dantela si dragoste . Partea superioară este realizată din dantelă fină, atent aleasă pentru desenul ei delicat, aproape vegetal, care urmărește linia corpului cu o naturalețe desăvârșită. Acestea nu domină textura, ci o amplifică, creând profunzime și un joc discret de reflexii care se trezesc la fiecare pas. Mânecile lungi, transparente , inobilare cu dantela, prelungesc firesc linia bustului, oferind senzația unei pieli îmbrăcate în lumină. Decolteul adânc din spate, curat și elegant, este susținut de o construcție impecabilă, fără artificii vizibile . Talia este sugerată cu finețe, permițând fustei să se nască natural din linia corpului. Partea inferioară este realizată din tul de mătase fin, aerat, stratificat cu măiestrie pentru a obține volum prin suprapunere, nu prin rigidizare. Căderea este fluidă, aproape respirată, iar transparența este controlată cu delicatețe. Dincolo de tehnică, rochia vorbește despre echilibru. Partea de sus poartă memoria timpului, a răbdării și a gesturilor repetate în atelier — o poveste brodată pe piele. Partea de jos este libertatea pură: aer, mers, dans, promisiune. Este o rochie de mireasa care nu caută să domine, ci să însoțească, născută parcă dintr-o lumină blândă de dimineață, când totul este fragil și posibil.',
    rentPrice: 4200,
    price: 6900,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Lumiere/IMG_5440.PNG',
    images: ['/images/Imperial/Lumiere/IMG_5440.PNG', '/images/Imperial/Lumiere/IMG_5439.jpg', '/images/Imperial/Lumiere/IMG_5567.PNG'],
    sketches: ['/images/Imperial/Lumiere/lumiere_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Dantelă fină, tul de mătase', silhouette: 'Prințesă', neckline: 'V-Neck' }
  },
  {
    id: 'imperial-queen',
    name: 'Queen',
    description: 'Rochia de mireasa Queen este expresia pură a eleganței regale. Corsajul cu linii curate și decolteu pătrat subliniază armonios silueta, oferind un aer sofisticat și echilibrat. Talia bine definită marchează începutul unei croieli A-line , a unei fuste ample, spectaculoase, care se deschide cu grație într-o trenă bogată, conferind rochiei o prezență impunătoare. Spatele impresionează prin decupajul elegant în formă de lacrimă, completat de un șir delicat de nasturi, detaliu ce adaugă profunzime și rafinament designului. Materialul nobil, o tafta impecabila , cu ținută perfectă, susține volumul rochiei și creează o siluetă demnă de o apariție regală. Queen este rochia miresei care pășește cu siguranță, calm și grație — o regină în propria poveste.',
    rentPrice: 4200,
    price: 5900,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Queen/IMG_5571.jpg',
    images: ['/images/Imperial/Queen/IMG_5571.jpg', '/images/Imperial/Queen/IMG_5463.jpg', '/images/Imperial/Queen/IMG_5568.jpg'],
    sketches: ['/images/Imperial/Queen/queen_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Alb'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tafta impecabilă', silhouette: 'A-Line / Prințesă', neckline: 'Pătrat' }
  },
  {
    id: 'imperial-serena',
    name: 'Serena',
    description: 'Serena , este rochia de mireasa care urmărește delicat liniile corpului, evidențiind silueta într-un mod armonios și feminin. Croiala tip sirenă alungește vizual trupul, iar materialul fin cade fluid, creând o mișcare elegantă la fiecare pas. Bustul este realizat din tulle transparent, decorat bogat cu aplicații din dantelă cusute manual, conturate cu mărgele fine ce adaugă strălucire subtilă și profunzime. Decolteul în V, atât în față cât și în spate, oferă un aer sofisticat și romantic, echilibrat perfect de mânecile scurte din dantelă delicată. Spatele este spectaculos, dar păstrează o notă de finețe, iar trena discretă completează rochia cu un aer regal și diafan. Este o rochie care vorbește despre feminitate, rafinament și o frumusețe atemporală.',
    rentPrice: 3800,
    price: 4500,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Serena/IMG_5423.jpg',
    images: ['/images/Imperial/Serena/IMG_5423.jpg', '/images/Imperial/Serena/IMG_5424.jpg', '/images/Imperial/Serena/IMG_5460.jpg', '/images/Imperial/Serena/IMG_5573.jpg'],
    sketches: ['/images/Imperial/Serena/serena_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tulle transparent, dantelă', silhouette: 'Sirenă', neckline: 'V-Neck' }
  },
  {
    id: 'imperial-mayson',
    name: 'Mayson',
    description: 'Această rochie de mireasa din tafta albă cu irizații fine argintii nu este doar o ținută, ci o declarație. Creată pentru femeia puternică, sigură pe sine, care pășește cu eleganță și lasă în urmă o impresie de neuitat, rochia îmbină noblețea clasică cu o forță subtilă, dar incontestabilă. Croiala amplă, cu fustă bogată și trenă delicată, conturează o siluetă impunătoare, în timp ce talia bine definită subliniază feminitatea într-o manieră echilibrată și rafinată. Mânecile lungi adaugă un aer solemn și sofisticat, evocând eleganța atemporală a unei prezențe regale. Decolteul adânc în formă de V, atât în față, cât și în spate, dezvăluie cu măsură, sugerând mai mult decât arătând, și oferă un contrast perfect între delicatețe și autoritate. Textura specială a taftalei, cu reflexii argintii discrete, prinde viață în lumină, asemenea unei armuri diafane — strălucitoare, dar fină. Este o rochie de mireasa pentru femeia care paseste cu grație, dar care își cunoaște valoarea și își exprimă puterea printr-o ținută impecabilă, purtată cu naturalețe și demnitate. O apariție memorabilă, destinată să rămână în priviri și în amintiri.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/Imperial/Mayson/IMG_5366.jpg',
    images: ['/images/Imperial/Mayson/IMG_5366.jpg', '/images/Imperial/Mayson/IMG_5364.jpg', '/images/Imperial/Mayson/IMG_5369.jpg', '/images/Imperial/Mayson/IMG_5370.jpg'],
    sketches: ['/images/Imperial/Mayson/mayson_sketch.png'],
    currency: 'RON',
    sizes: ['38', '40'],
    colors: ['Alb cu irizații argintii'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tafta albă', silhouette: 'A-Line / Amplă', neckline: 'V-Neck profund' }
  },
  {
    id: 'evora-evora',
    name: 'Evora',
    description: 'Pășește în propria ta poveste cu această rochie de mireasă, care este o creație diafană, o simfonie a texturilor fine și a strălucirii discrete. Concepută pentru mireasa care visează la o eleganță atemporală, dar care își dorește să strălucească la propriu, această rochie îmbină romantismul clasic al mânecilor lungi diafane cu senzualitatea modernă a unui corset bijuterie. Structura de bază este tip A-line, oferind volum fluid din multiple straturi de tul fin, iar trena fluidă adaugă dramatism regal. Corsetul are decolteu amplu în V și este bogat ornamentat cu broderii tridimensionale, perle, cristale și paiete aplicate ce curg în cascadă spre talie, oferind un aer de lux și aristocrație.',
    rentPrice: 4400,
    price: 8900,
    type: DressType.BUY,
    imageUrl: '/images/Evora/IMG_5580.jpg',
    images: ['/images/Evora/IMG_5580.jpg', '/images/Evora/IMG_5581.jpg', '/images/Evora/IMG_5583.jpg', '/images/Evora/IMG_5587.jpg'],
    sketches: ['/images/Evora/evora_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Ivory / Nude subtil'],
    collection: Collection.EVORA,
    details: { fabric: 'Tul fin, broderii 3D, perle și cristale', silhouette: 'Prințesă / A-Line', neckline: 'V-Neck cu aspect Illusion' }
  },
  {
    id: 'anna-annador',
    name: 'Annador',
    description: 'Această rochie de mireasă tip A-line îmbină armonios rafinamentul tehnic cu o eleganță atemporală. Bustul este realizat pe o bază structurată, evidențiat de un decolteu în formă de inimă, care conturează delicat linia umerilor. Dantela fină, aplicată manual, formează un desen floral sofisticat, cu arabescuri atent brodate ce adaugă textură și profunzime. Talia este bine definită, oferind susținere și subliniind silueta, iar închiderea discretă la spate păstrează linia curată a corsajului. Fusta amplă din straturi vaporoase de tull cade fluid, construind un volum echilibrat, specific croielii A-line, și se prelungește într-o trenă delicată ce adaugă mișcare și grație. Poetic, rochia pare desprinsă dintr-un vis luminos: dantela înflorește pe bust precum o grădină sculptată în fir de mătase, iar fusta plutește ușor la fiecare pas, ca o adiere caldă de vară. Este o piesă care nu doar îmbracă mireasa, ci o învăluie într-o aură regală, discretă și profund feminină.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Annador/BBACE0F9-1649-4353-93B4-A7D453D0991C.PNG',
    images: ['/images/ANNA/Annador/0DB5AAD1-EEE2-40B7-926B-403B31D9EEE2.PNG', '/images/ANNA/Annador/BBACE0F9-1649-4353-93B4-A7D453D0991C.PNG'],
    sketches: ['/images/ANNA/Annador/anna_annador_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Dantelă fină, tull', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'anna-anais',
    name: 'Anais',
    description: 'Rochia de mireasa Anais, plutește ca un vis nerostit, îmbrăcând silueta într-o poezie de sclipiri, buline fine și transparențe delicate. Bustul dantelat cu migală pare să adune constelații întregi, coborând ușor spre o fustă amplă, vaporoasă, care curge ca o ceață de dimineață peste pajiști tăcute. Trena ușoară lasă în urmă o urmă de basm, ca și cum Anais nu ar păși, ci ar pluti spre o poveste scrisă doar pentru ea. O creație diafană cu siluetă A-line, realizată din tull fin decorat cu bulinuțe de diverse mărimi și presărat cu sclipici delicat, ce captează subtil lumina la fiecare mișcare. Bustul este evidențiat de un decolteu adânc în formă de V, bogat ornamentat cu dantelă aplicată manual, mărgele și pietre strălucitoare, pentru un efect sofisticat și rafinat. Mânecile lungi, bufante, cu manșete elegante, completează armonios designul romantic al rochiei. O alegere perfectă pentru o mireasă modernă, care își dorește eleganță regală și lejeritate în același timp.',
    rentPrice: 4300,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anais/A85332DF-BE08-4DA1-9DF5-CF48706FFDBF.PNG',
    images: ['/images/ANNA/Anais/79DC5387-A233-4FAF-A400-365F22270EED.PNG', '/images/ANNA/Anais/A85332DF-BE08-4DA1-9DF5-CF48706FFDBF.PNG', '/images/ANNA/Anais/0A1909F0-C8B1-4B7C-AA3E-2514FAA0D407.jpg'],
    currency: 'RON',
    sizes: ['36', '38', '40', '42'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Tull cu bulinuțe, sclipici fin', silhouette: 'A-Line', neckline: 'V-Neck adânc' }
  },
  {
    id: 'anna-anaria',
    name: 'Anaria',
    description: 'O rochie de mireasă cu o eleganță regală, creată pentru o apariție memorabilă. Silueta A-line alungește delicat linia corpului, iar fusta amplă din tull fin, cu particule discrete strălucitoare, cade fluid și aerat, oferind un efect diafan la fiecare pas. Bustul este realizat din dantelă bogat brodată manual cu mărgele și perlute fine, dispuse simetric, evidențiind decolteul în V și conturând armonios talia. Spatele continuă aceeași linie elegantă, cu un V generos și închidere tip corset cu șnur satinat împletit, pentru ajustare perfectă și susținere optimă. Mânecele ușor bufante din tull transparent adaugă romantism și delicatețe, fiind decorate pe antebraț și manșetă cu aplicații prețioase din dantelă, perle și mărgele, ce reflectă subtil lumina. O rochie ce îmbină finețea detaliilor couture cu grația unei prințese moderne.',
    rentPrice: 3200,
    price: 4900,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anaria/753C58D1-6014-43EF-B408-E9D5382C43EE.PNG',
    images: ['/images/ANNA/Anaria/48777E20-17E8-4147-8162-1DFA6FC8ED37.PNG', '/images/ANNA/Anaria/753C58D1-6014-43EF-B408-E9D5382C43EE.PNG', '/images/ANNA/Anaria/E110F78F-1AE3-4F76-9927-C1C38242F2B0.PNG'],
    sketches: ['/images/ANNA/Anaria/anna_anaria_sketch.png'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Dantelă cu perle, tull fin cu sclipici', silhouette: 'A-Line', neckline: 'V-Neck' }
  },
  {
    id: 'anna-anastasia',
    name: 'Anastasia',
    description: 'Această rochie de mireasă impresionează prin echilibrul perfect dintre rafinament regal și delicatețe modernă. Croiala A-line alungește silueta și creează o linie fluidă, diafană, în timp ce bustul este realizat pe suport de tul nude (culoarea pielii), evidențiat de un decolteu în inimă subtil conturat de aplicații florale din dantelă brodată manual cu mărgele fine. Spatele este spectaculos: tul transparent nude, încadrat perimetral de dantelă aplicată și închis cu un șir elegant de năsturei îmbrăcați, care coboară delicat pe linia coloanei. Fusta amplă din tul ivory cade lejer, în straturi vaporoase, formând o trenă fină ce adaugă mișcare și grație fiecărui pas. O creație romantică, aerată și sofisticată, gândită pentru mireasa care își dorește să strălucească natural, cu eleganță atemporală.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anastasia/20FF0E7B-AEEA-4216-A8BD-DB3ED5252E97.PNG',
    images: ['/images/ANNA/Anastasia/20FF0E7B-AEEA-4216-A8BD-DB3ED5252E97.PNG', '/images/ANNA/Anastasia/811DDE31-7EB2-44F1-8D33-920F6E536A1E.PNG', '/images/ANNA/Anastasia/9882240D-72F9-435F-9A1C-213C53DC6380.PNG'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Ivory / Nude'],
    collection: Collection.ANNA,
    details: { fabric: 'Tul fin nude, dantelă brodată', silhouette: 'A-Line', neckline: 'Inimă / Subtil conturat' }
  },
  {
    id: 'anna-anastea',
    name: 'Anastea',
    description: 'Rochie de mireasă din satin fin, cu structură amplă tip A-line și talie bine definită, ce conturează silueta cu eleganță. Bustul este delicat drapat, cu umeri căzuți și mâneci bufante scurte, oferind echilibru între rafinament și romantism. Corsetul se închide la spate cu șnur satin împletit, asigurând susținere perfectă și o ajustare armonioasă pe corp, asemenea unei promisiuni legate cu grijă. Fusta amplă, construită din pliuri fluide în partea din spate, se continuă într-o trenă lungă și diafană, care curge grațios și prinde lumina la fiecare pas, ca o poveste de dragoste scrisă în satin alb.',
    rentPrice: 4200,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anastea/C5E124D3-D23F-46C6-9FFF-B48DBC1B5C58.PNG',
    images: ['/images/ANNA/Anastea/C5E124D3-D23F-46C6-9FFF-B48DBC1B5C58.PNG', '/images/ANNA/Anastea/162B7262-5C38-4385-9346-FDB3B1527BD4.PNG', '/images/ANNA/Anastea/22696034-4E9C-4BE8-AAE9-528DBC3C1ED7.PNG', '/images/ANNA/Anastea/IMG_6002.jpg'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Satin fin', silhouette: 'A-Line', neckline: 'Drapat / Umeri căzuți' }
  },
  {
    id: 'anna-anatolia',
    name: 'Anatolia',
    description: 'Rochia de mireasă ANATOLIA este o piesă de o eleganță rafinată, cu un aer romantic și eteric, care atrage imediat privirea prin armonia dintre volum, transparență și detaliu artizanal. Fusta este amplă, de tip prințesă, realizată din straturi generoase de tulle fin, ușor sidefat, care conferă lejeritate și mișcare. Volumul este bine echilibrat, iar trena delicată se prelungește natural, adăugând un plus de dramatism și noblețe fără a încărca silueta. Pe întreaga suprafață a fustei sunt aplicate motive florale tridimensionale, dispuse aerisit, ca și cum ar pluti. Florile sunt realizate din dantelă fină și organza, cu petale ușor reliefate, ceea ce creează un efect poetic, aproape de grădină feerică. Bustul este construit dintr-un tulle extrem de fin și transparent, creând efectul de illusion bodice, lăsând impresia că dantela este „tatuată” direct pe piele. Dantela urmează linia corpului într-un mod foarte natural, punând în valoare talia și bustul fără a fi ostentativă. Decolteul este delicat, elegant, iar linia sa este îmblânzită de aplicațiile florale care se continuă fluid spre umeri și mâneci. Mânecile lungi, realizate din același tulle transparent, sunt decorate cu dantelă aplicată manual. Un detaliu esențial îl reprezintă dantela bogat ornamentată cu paiete minuscule și mărgele fine, integrate subtil în motivul floral.',
    rentPrice: 4500,
    price: 6900,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anatolia/IMG_5855.jpg',
    images: ['/images/ANNA/Anatolia/IMG_5855.jpg', '/images/ANNA/Anatolia/IMG_5851.jpg'],
    currency: 'RON',
    sizes: ['38', '40'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Tulle fin, flori 3D', silhouette: 'Prințesă', neckline: 'Illusion cu flori' }
  },
  {
    id: 'anna-anelie',
    name: 'Anelie',
    description: 'Bustul este integral cusut manual în mărgele și aplicații fine, dispuse dens pentru a crea un efect tridimensional și o textură sofisticată. Broderia urmărește liniile corsetului, evidențiind construcția acestuia și subliniind talia. Decolteul este un V profund, specific corsetului, care coboară elegant până în linia taliei, alungind optic trunchiul și accentuând silueta. V-ul este susținut de structura internă a corsetului, ce oferă stabilitate și susținere, modelând delicat bustul. Construcția corsetului este completată la spate de un sistem de închidere cu șiret (lace-up), care permite ajustarea perfectă pe corp și evidențiază linia taliei. Balenele integrate asigură susținere și o formă sculpturală, păstrând în același timp finețea designului. Din zona bustului pornesc fronséuri delicate din tulle fin, care cad lejer peste umeri și formează o mânecă căzută, vaporoasă. Acestea adaugă volum subtil în partea superioară și echilibrează proporțiile, oferind un aer romantic și eteric. Fusta este realizată dintr-o succesiune amplă de straturi de tulle fin, suprapuse gradual pentru a crea volum fără greutate. Construcția A-line pornește din talie și se deschide progresiv, alungind silueta și conferind fluiditate mișcării. Straturile multiple de tulle creează un efect diafan, ușor vaporos, cu o cădere naturală și elegantă.',
    rentPrice: 4200,
    price: 6900,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anelie/309257BD-2244-49A4-A5D5-50358890D6D5.PNG',
    images: ['/images/ANNA/Anelie/309257BD-2244-49A4-A5D5-50358890D6D5.PNG', '/images/ANNA/Anelie/3F333F5B-B61B-4A2E-87D1-8325BBA0CBF7.PNG', '/images/ANNA/Anelie/B16FAF52-4CD5-4C75-A5D3-04E5ECE96EEB.PNG'],
    currency: 'RON',
    sizes: ['48', '50', '52'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Mărgele dense, tulle fin', silhouette: 'A-Line / Corset', neckline: 'V-Profund' }
  },
  {
    id: 'anna-anamaria',
    name: 'Anamaria',
    description: 'Rochia de mireasa Anamaria evocă farmecul prințeselor zilelor noastre, îmbinând eleganța clasică cu un aer diafan. Realizată din tul fin, impresionează prin partea superioară delicat construită, cu mâneci lungi, un decolteu extrem de discret și un guler rusesc subtil. Elementul său distinctiv îl reprezintă mărgelele fine, aplicate cu migală, care se aștern asemenea unei ploi strălucitoare peste bust și mâneci, adăugând un plus de rafinament și romantism. Rochia de mireasă impresionează printr-un aer rafinat și romantic, tulle-ul fin, cu o cădere lejeră și ușor vaporoasa intregind imaginea. Partea din spate este delicat decorată cu margele prețioase și aplicații fine, care se continuă armonios pe mânecile lungi, transparente, oferind un plus de eleganță și feminitate. Corsajul este bine definit, subliniind talia, iar fusta amplă curge fluid până la podea, creând o siluetă grațioasă și echilibrată. Spatele spectaculos, închis cu un șir generos de nasturi din sticlă, care pornesc din zona gâtului și coboară delicat pe linia spatelui adaugă un detaliu sofisticat și luminos, transformând spatele rochiei într-un element memorabil, extrem de feminin și elegant.',
    rentPrice: 4200,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anamaria/IMG_5841.jpg',
    images: ['/images/ANNA/Anamaria/IMG_5841.jpg', '/images/ANNA/Anamaria/IMG_5829.jpg', '/images/ANNA/Anamaria/IMG_5843.jpg', '/images/ANNA/Anamaria/IMG_5845.jpg'],
    currency: 'RON',
    sizes: ['40', '42'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Tull fin, mărgele fine', silhouette: 'Prințesă', neckline: 'Guler rusesc discret' }
  },
  {
    id: 'anna-annabelle',
    name: 'Annabelle',
    description: 'Această rochie de mireasă este o adevărată declarație de eleganță și rafinament, creată pentru mireasa care își dorește să strălucească într-un mod natural, dar memorabil. Corsetul atent structurat, cu un decolteu în V amplu ce coboară armonios până în linia taliei, alungește silueta și pune în valoare formele într-un mod delicat și sofisticat. Fiecare detaliu este gândit pentru a evidenția feminitatea și grația purtătoarei, oferind un echilibru perfect între senzualitate și eleganță. Rochia de mireasa Anabell este acoperită în întregime cu un tul fin, ușor ca o adiere, care îmbracă silueta într-o aură de delicatețe. Broderiile din dantelă, lucrate cu măiestrie, sunt îmbogățite cu mărgele și paiete fine ce captează lumina la fiecare pas, creând un efect subtil de strălucire. Aceste detalii prețioase adaugă profunzime și un farmec aparte, fără a încărca vizual designul, ci dimpotrivă, accentuând noblețea rochiei. Un element definitoriu al acestei creații este linia umerilor, frumos evidențiată, care conferă rochiei un aer regal și echilibrat. Întregul design emană armonie și rafinament, transformând rochia într-o piesă spectaculoasă, ce îți pune în valoare frumusețea într-un mod care îți taie respirația.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Annabelle/IMG_5872.jpg',
    images: ['/images/ANNA/Annabelle/IMG_5872.jpg', '/images/ANNA/Annabelle/IMG_5875.jpg', '/images/ANNA/Annabelle/IMG_5881.jpg', '/images/ANNA/Annabelle/IMG_5868.jpg'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Tul fin, dantelă cu paiete', silhouette: 'A-Line / Prințesă', neckline: 'V-Neck amplu' }
  },
  {
    id: 'anna-anavelle',
    name: 'Anavelle',
    description: 'O apariție care pare desprinsă dintr-un vis regal, această rochie de mireasă îmbină romantismul delicat cu rafinamentul tehnic al haute couture-ului bridal. Silueta A-line, atemporală și feminină, alungește armonios linia corpului, oferind lejeritate, grație și o cădere spectaculoasă a fustei. Bustul este realizat pe suport fin de tull ivory, îmbrăcat într-o cascada sofisticată cu aplicații bogate din mărgele fine și micro-paiete cusute manual. Broderia este dispusă artistic, cu un efect radiant care pornește din zona bustului și taliei și curge delicat spre fustă, creând o tranziție naturală și fluidă între partea structurată și volumul eterat al tull-ului. Spatele este un adevărat punct de atracție: realizat integral din tull transparent tip „illusion”, se închide elegant cu un șir vertical de năsturei din sticlă, ce urcă delicat până aproape de gât. Aplicațiile din margelate sunt poziționate strategic pentru a evidenția linia spatelui și pentru a continua armonios în talie, unde broderia se estompează treptat în fusta amplă. Fusta A-line este confecționată din straturi fine de tull ivory, ușor sidefat, care captează lumina subtil și creează un efect aerat, aproape cinematografic în mișcare. Trena completează designul cu un plus de dramatism și eleganță regală, păstrând totodată lejeritatea și confortul.',
    rentPrice: 4200,
    price: 6900,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Anavelle/FC5646E0-8C55-4E53-B5C4-FE51E2B46449.PNG',
    images: ['/images/ANNA/Anavelle/F0984693-7165-430E-A06E-8451F8492F3A.PNG', '/images/ANNA/Anavelle/A74C3A1A-C6FF-4C80-BBF4-6E3736B9F525.PNG', '/images/ANNA/Anavelle/FC5646E0-8C55-4E53-B5C4-FE51E2B46449.PNG'],
    currency: 'RON',
    sizes: ['44', '46', '48', '50'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Tull ivory, mărgele și paiete', silhouette: 'A-Line', neckline: 'V-Shape iluzie' }
  },
  {
    id: 'anna-just-anna',
    name: 'Just Anna',
    description: 'Este o rochie de mireasă romantică și elegantă, cu un aer ușor boem-regal. Corsetul este piesa de rezistență: bogat decorat cu broderii și aplicații delicate, care creează un efect luxos, dar nu încărcat. Decolteul este off-shoulder, iar mânecile bufante, din tul transparent, îi dau un look diafan, aproape eteric, foarte feminin. Taliei îi este oferită o definiție frumoasă, iar fusta lungă, amplă, din straturi vaporoase de tul, cade lejer și curge elegant, creând un efect de ușurință și rafinament la fiecare pas. Micile accente strălucitoare din material prind subtil lumina, fără să fie ostentative. Spatele rochiei este absolut fermecător. Corsetul este delicat structurat, cu un joc elegant de transparențe și broderii fine care par să se topească ușor pe piele. Șnurul încrucișat adaugă un aer romantic și clasic, punând în valoare talia într-un mod foarte feminin. Mânecile căzute, vaporoase, completează perfect linia spatelui, dând un sentiment de lejeritate și grație. Fusta pornește amplu de sub talie, din straturi fine de tulle ușor sidefat, care cad lin și creează o siluetă de poveste.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Just Anna/IMG_5889.jpg',
    images: ['/images/ANNA/Just Anna/IMG_5889.jpg', '/images/ANNA/Just Anna/IMG_5890.jpg', '/images/ANNA/Just Anna/IMG_5908.jpg'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.ANNA,
    details: { fabric: 'Tulle sidefat, broderii fine', silhouette: 'Prințesă', neckline: 'Off-shoulder' }
  },
  {
    id: 'anna-annette',
    name: 'Annette',
    description: 'Linia taliei este bine definită, evidențiind armonios formele, iar de aici pornește o fustă amplă, în stil prințesă, ce conferă rochiei un aer regal și spectaculos. Fusta este realizată din organza ușoara și vaporosa, care se mișcă grațios la fiecare pas și creează un efect diafan, perfect pentru o apariție memorabilă. Volumul echilibrat și fluiditatea materialului oferă confort, dar și un aer boem. Bustul este fronsat, cu un design delicat în formă de inimă, evidențiat de reflexii subtile rozé care adaugă profunzime și un aer sofisticat. Talia este bine definită, alungind silueta și oferind un echilibru armonios între volum și eleganță. Modelul este versatil și poate fi purtat în două variante de styling: cu mâneci căzute, pentru un look romantic, diafan și senzual, sau cu mâneci bufante, pentru un efect regal, modern și statement. Această flexibilitate permite personalizarea rochiei în funcție de personalitatea miresei și stilul evenimentului. O rochie care îmbină rafinamentul tehnic cu o poveste romantică, creată pentru mireasa care își dorește să se simtă prințesă, fără a renunța la lejeritate și naturalețe.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/ANNA/Annette/IMG_5917.jpg',
    images: ['/images/ANNA/Annette/IMG_5917.jpg', '/images/ANNA/Annette/IMG_5918.jpg', '/images/ANNA/Annette/IMG_5919.jpg', '/images/ANNA/Annette/35C61BE9-0D54-4949-881A-50C8B2229576.PNG', '/images/ANNA/Annette/IMG_5920.PNG'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory / Rozé'],
    collection: Collection.ANNA,
    details: { fabric: 'Organza ușoară, broderie', silhouette: 'Prințesă', neckline: 'Inimă / Off-shoulder curbat' }
  },
  {
    id: 'mayra-adania',
    name: 'Adania',
    description: 'Adania este un poem scris în tull fin și dantelă florale tridimensionale. Bustul în formă de inimă este un spectacol de delicatețe, brodat cu o măiestrie desăvârșită ce onorează liniile naturale ale feminității. Mânecile căzute adaugă o notă romantică, eterică, ca un suspin de primăvară. Silueta A-line se deschide amplu, îmbrăcând fiecare pas într-o aură de poveste.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Adania/IMG_5597.jpg',
    images: [
      '/images/MAYRA/Adania/5F1C2FC7-5BFA-4C1B-82A7-DB01945D2FD5.png',
      '/images/MAYRA/Adania/IMG_5591.jpg',
      '/images/MAYRA/Adania/IMG_5597.jpg',
      '/images/MAYRA/Adania/IMG_5603.jpg',
      '/images/MAYRA/Adania/IMG_5607.jpg',
      '/images/MAYRA/Adania/IMG_6058.PNG'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-celina',
    name: 'Celina',
    description: 'Celina reprezintă grația atemporală, capturată arhitectural în straturi de tull fin ca aerul de dimineață. Bustul generos ornamentat cu flori tridimensionale pare sculptat din lumină, continuându-se fluid pe o fustă amplă ce îmbrățișează pământul. Este o rochie pentru mireasa care își dorește să fie, simultan, o prezență impunătoare și o amintire difuză, de neuitat.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Celina/IMG_5616.jpg',
    images: [
      '/images/MAYRA/Celina/IMG_5616.jpg',
      '/images/MAYRA/Celina/IMG_5618.jpg',
      '/images/MAYRA/Celina/IMG_5620.jpg',
      '/images/MAYRA/Celina/IMG_5626.JPEG',
      '/images/MAYRA/Celina/IMG_6063.PNG'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-desideria',
    name: 'Desideria',
    description: 'Desideria transformă dorința în materie palpabilă. Cu o fustă monumentală ce plutește în siajul fiecărei mișcări, această creație redefinește romantismul modern. Dantela spectaculoasă dansează pe corsajul bine definit, lăsând linia gâtului să respire sub un fin decolteu în inimă. Fiecare aplicare 3D este o declarație, iar întregul este o operă desăvârșită dedicată momentelor eterne.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Desideria/IMG_5631.jpg',
    images: [
      '/images/MAYRA/Desideria/IMG_5640.jpg',
      '/images/MAYRA/Desideria/IMG_5631.jpg',
      '/images/MAYRA/Desideria/IMG_5637.jpg',
      '/images/MAYRA/Desideria/IMG_5638.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-elvira',
    name: 'Elvira',
    description: 'Elvira amintește de eleganța curților aristocratice, rescrisă pentru sufletul contemporan. Broderia opulentă, așezată pe un suport de tull irezistibil de moale, se pierde discret în fusta amplă, sugerând mister și sofisticare. Silueta sa alungită este completată de tranziții perfecte între clar și iluzie, perfectă pentru o prezență absolut memorabilă.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Elvira/IMG_5648.jpg',
    images: [
      '/images/MAYRA/Elvira/IMG_5648.jpg',
      '/images/MAYRA/Elvira/09616BBB-2A47-4431-BF95-DD0C63726679.PNG',
      '/images/MAYRA/Elvira/IMG_5651.jpg',
      '/images/MAYRA/Elvira/IMG_5652.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-grazia',
    name: 'Grazia',
    description: 'Grazia este însăși fluiditatea. O cascadă de tull imaculat ce cade, se adună și se ridică lăsând în urmă o trenă spectaculoasă. Partea superioară este o rețea rafinată de broderii ce mângâie linia bustului, lăsând umerii goi să dicteze sensibilitatea întregii ținute. Este rochia unde arta întâlnește inocența pură.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Grazia/IMG_5668.jpg',
    images: [
      '/images/MAYRA/Grazia/IMG_5668.jpg',
      '/images/MAYRA/Grazia/ED2F8FEC-0716-44BC-B7C6-29E39267E930.jpg',
      '/images/MAYRA/Grazia/IMG_5669.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-isadora',
    name: 'Isadora',
    description: 'Isadora este croită pentru o melodie vizuală. Această creație A-line combină rigoarea tehnică a unui corset impecabil cu o nestăpânită cascadă de aplicații florale, risipite parcă de un vânt blând de mai. Este rochia ce asigură libertatea mișcării, păstrând în același timp un aer solemn, luxos și inegalabil.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Isadora/IMG_5681.jpg',
    images: [
      '/images/MAYRA/Isadora/IMG_5681.jpg',
      '/images/MAYRA/Isadora/IMG_5682.jpg',
      '/images/MAYRA/Isadora/IMG_5691.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-luminia',
    name: 'Luminia',
    description: 'Așa cum îi spune și numele, Luminia este țesută din lumina lunii. Un joc fascinant de reflexii ascunse între straturile de tull, completate de structuri florale 3D minuțios poziționate. Spatele este o adevărată capodoperă a iluziei, dezvăluind și ascunzând deopotrivă, pentru o apariție absolut fermecătoare.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Luminia/IMG_5697.jpg',
    images: [
      '/images/MAYRA/Luminia/IMG_5697.jpg',
      '/images/MAYRA/Luminia/IMG_5698.jpg',
      '/images/MAYRA/Luminia/IMG_5699.jpg',
      '/images/MAYRA/Luminia/IMG_5709.jpg',
      '/images/MAYRA/Luminia/IMG_5710.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-miracle',
    name: 'Miracle',
    description: 'Miracle este momentul în care magia devine vizibilă. O rochie cu volume excepționale, dar inexplicabil de ușoară. Dantelăria frontală curge neîntrerupt pe linia fustei, dând senzația de continuitate naturală. Silueta sa curajoasă este echilibrată de elementele romantice, devenind o veritabilă ținută statement.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Miracle/IMG_5714.jpg',
    images: [
      '/images/MAYRA/Miracle/IMG_5714.jpg',
      '/images/MAYRA/Miracle/IMG_5715.jpg',
      '/images/MAYRA/Miracle/IMG_5717.jpg',
      '/images/MAYRA/Miracle/IMG_5718.jpg',
      '/images/MAYRA/Miracle/IMG_5727.jpg',
      '/images/MAYRA/Miracle/IMG_5729.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-roze',
    name: 'Roze',
    description: 'Roze poartă în firele sale promisiunea primelor iubiri. Subtilă, cu nuanțe rafinate de fildeș ce se îmbină cu transparențe diafane, rochia aduce în prim-plan broderii florale cu un farmec retro, reimaginat pentru azi. Trena lungă adaugă grație, în timp ce talia marcată asigură conturul perfect feminin.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Roze/IMG_5736.jpg',
    images: [
      '/images/MAYRA/Roze/IMG_5736.jpg',
      '/images/MAYRA/Roze/IMG_5198.heic',
      '/images/MAYRA/Roze/IMG_5735.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-snow',
    name: 'Snow',
    description: 'Snow este esența purității absolute, surprinsă în mătase și tull iluzie. Curată, imaculată, rochia impresionează prin simplitatea formei, animată doar de bogăția aplicațiilor fine care apar, ca fulgii de nea, fix acolo unde e nevoie de prețiozitate. O abordare modernă a clasicei albe, pentru mireasa minimalistă, dar sofisticată.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Snow/IMG_5744.jpg',
    images: [
      '/images/MAYRA/Snow/IMG_5744.jpg',
      '/images/MAYRA/Snow/IMG_5743.jpg',
      '/images/MAYRA/Snow/IMG_5748.jpg',
      '/images/MAYRA/Snow/IMG_5753.jpg',
      '/images/MAYRA/Snow/IMG_5757.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-tania',
    name: 'Tania',
    description: 'Tania este seducția ascunsă în decență. Această piesă masterclass în design integrează bretele subțiri, lăsând decolteul să devină un panou de expunere pentru o dantelă incredibil de prețioasă. Fusta cade greu, dar se mișcă lejer, creând acel efect dramatic, sculptural, apreciat pe marile reviste de modă.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Tania/IMG_5764.jpg',
    images: [
      '/images/MAYRA/Tania/IMG_5764.jpg',
      '/images/MAYRA/Tania/1BE5E875-06ED-49AB-84CD-D35C66C4E836.PNG',
      '/images/MAYRA/Tania/IMG_5767.jpg',
      '/images/MAYRA/Tania/IMG_5771.jpg',
      '/images/MAYRA/Tania/IMG_5781.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  },
  {
    id: 'mayra-taniana',
    name: 'Taniana',
    description: 'Taniana este o simfonie a naturii imprimată pe material. Creația este asaltată vizual de o avalanșă de ramuri și flori brodate, care se cațără lin pe trup. Cu un spate generos decupat și un decolteu frontal plin de curaj, Taniana nu face compromisuri când vine vorba de lux și excentricitate.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/MAYRA/Taniana/IMG_5785.jpg',
    images: [
      '/images/MAYRA/Taniana/IMG_5785.jpg',
      '/images/MAYRA/Taniana/9AD74CD5-0193-4055-9F4D-F6AEEA3289AF.PNG',
      '/images/MAYRA/Taniana/IMG_5788.jpg',
      '/images/MAYRA/Taniana/IMG_5796.jpg'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.MAYRA,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  }
  ,
  {
    id: 'beverly-anamara',
    name: 'Anamara',
    description: 'Anamara din colecția Beverly este un vis boem, așezat pe straturi infinit de fine de tull. Elementul ei definitoriu este fluiditatea—rochia pare mereu în mișcare, chiar și în repaus. Cu un decolteu generos, broderii tridimensionale rafinate și o fustă care plutește eteric, Anamara este dedicată spiritelor libere, aducând un suflu de eleganță organică și naturală într-un design ireproșabil couture.',
    rentPrice: 4000,
    price: 6000,
    type: DressType.BUY,
    imageUrl: '/images/BEVERLY/Anamara/1711CC8C-ED8F-40EF-83C7-60696BAAE99B.PNG',
    images: [
      '/images/BEVERLY/Anamara/03746EAE-477A-4A33-AE02-2AC1505D028A.jpg',
      '/images/BEVERLY/Anamara/1711CC8C-ED8F-40EF-83C7-60696BAAE99B.PNG',
      '/images/BEVERLY/Anamara/975368D7-5E16-45E5-B6B4-8664CA474BA6.PNG'
    ],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Ivory'],
    collection: Collection.BEVERLY,
    details: { fabric: 'Tull, dantelă 3D', silhouette: 'A-Line', neckline: 'Inimă' }
  }

];
