
import { Dress, DressType, Collection } from './types';

export const DRESSES: (Dress & { collection: Collection })[] = [
  {
    id: 'imperial-alma',
    name: 'Alma',
    description: 'Alma este acea rochie de mireasă care îmbină rafinamentul clasic cu o delicatețe modernă, rezultând o piesă diafană și feminină. Bustul este realizat pe structură de corset, oferind susținere și contur delicat siluetei, peste care se așază un strat de tulle extrem de fin. Acesta este decorat cu aplicații delicate din dantelă, dispuse armonios, iar marginile sunt cusute manual, evidențiind atenția desăvârșită pentru detalii și măiestria lucrului artizanal. Decolteul subtil și transparența controlată a tulle-ului creează un joc elegant între senzualitate și puritate. Spatele rochiei este pus în valoare de închiderea fină cu un sirag de nasturi din matase, care completează armonios designul bustului. Partea inferioară este compusă dintr-o fustă amplă și fluidă, realizată din mătase naturală în nuanță ivory, care curge lin și ușor la fiecare pas.',
    rentPrice: 5400,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/alma_front.jpg',
    images: ['/images/alma_front.jpg', '/images/alma_front_2.jpg', '/images/alma_back.jpg', '/images/alma_detail.jpg'],
    sketches: ['/images/alma_sketch_front_v3.png', '/images/alma_sketch_back.png', '/images/alma_sketch_movement.png'],
    currency: 'RON',
    sizes: ['54'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mătase naturală, Tulle fin, Dantelă', silhouette: 'A-Line / Fluidă', neckline: 'Decolteu subtil' }
  },
  {
    id: 'imperial-aurelia',
    name: 'Aurelia',
    description: 'Aurelia este o rochie de mireasă realizată din mătase naturală în nuanță Ivory, cu o cădere fluidă și greutate fină, care urmărește linia corpului fără a o constrânge. Silueta este fit & flare, cu talia subtil marcată și fusta ușor evazată, prelungită într-o trenă delicată, ce adaugă mișcare și noblețe mersului. Bustul este construit pe o bază structurată, cu decolteu în V, atât în față, cât și în spate, accentuat de o inserție discretă de tul. Aplicațiile de dantelă fină, brodată manual, se așază organic pe bust și umeri, coborând ca niște ramuri florale spre talie, unde se estompează treptat în textura mătăsii. Mânecile lungi, realizate din tul transparent, sunt decorate cu aceleași aplicații de dantelă, creând un contrast subtil între transparență și opacitate. Spatele impresionează prin șirul de nasturi fini îmbrăcați, care urmează linia coloanei și accentuează eleganța construcției. Interiorul este finisat impecabil, cu cusături curate și căptușeală din materiale naturale, gândite pentru confort și respirabilitate pe durata întregii zile.',
    rentPrice: 3600,
    price: 4800,
    type: DressType.BUY,
    imageUrl: '/images/aurelia_front.jpg',
    images: ['/images/aurelia_front.jpg', '/images/aurelia_back.jpg', '/images/aurelia_closeup.jpg', '/images/aurelia_detail.jpg'],
    currency: 'RON',
    sizes: ['38', '40'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mătase naturală, dantelă brodată manual, tul', silhouette: 'Fit & Flare', neckline: 'V-Neck cu inserție de tul' }
  },
  {
    id: 'imperial-argente',
    name: 'Argente',
    description: 'Rochia aceasta pare desprinsă dintr-un vis parizian, purtat pe străzi pavate de lumină caldă și emoție. Realizată din tafta albă cu irizații fine argintii, țesătura captează lumina într-un mod delicat, aproape diafan, creând un joc subtil de reflexii la fiecare mișcare. Materialul are acea structură specifică taftalei – fermă, dar fluidă – care îi permite să păstreze o linie impecabilă și să ofere volum fustei ample. Croiala este una clasică, cu talia bine marcată și o fustă amplă, în linie A, care cade generos până la podea, formând un cerc amplu în mers. Bustul este curat, minimalist, cu un decolteu rotund în față, ce echilibrează armonios dramatismul spatelui. În contrast, pe spate, rochia dezvăluie un decolteu adânc în V, elegant și feminin, care alungește silueta și adaugă un accent senzual discret. Mânecile lungi, perfect integrate în linia rochiei, sunt ornate de sus până jos cu năsturei albi din satin. Este o rochie care îmbină romantismul pur cu rigoarea croitoriei clasice – un echilibru între poezie și arhitectură textilă.',
    rentPrice: 3900,
    price: 5400,
    type: DressType.BUY,
    imageUrl: '/images/argente_front.jpg',
    images: ['/images/argente_front.jpg', '/images/argente_front_2.jpg', '/images/argente_back.jpg', '/images/argente_detail.jpg'],
    currency: 'RON',
    sizes: ['36', '38', '40'],
    colors: ['Alb cu irizații argintii'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tafta albă cu irizații, satin', silhouette: 'A-Line', neckline: 'Rotund / V-Shape pe spate' }
  },
  {
    id: 'imperial-daiana',
    name: 'Daiana',
    description: 'Aceasta rochie de mireasa este realizată din satin fin, mătăsos, extrem de plăcut la atingere, cu o suprafață netedă ce reflectă lumina delicat și elegant. Materialul are o cădere fluidă, urmărind linia corpului fără rigiditate și oferind confort la purtare si o structură rafinată. Croiala este feminină și minimalistă, cu un decolteu subtil în față, care conturează zona bustului într-un mod senzual, dar sofisticat. Talia este discret evidențiată, alungind vizual silueta, cu ajutorul franceurilor din partea superioara a fustei, cu linie dreaptă, care creează un efect elegant și aerisit. Mânecile lungi, ușor evazate, adaugă mișcare și lejeritate, completând armonios designul. Elementul central al rochiei este decolteul adânc în V pe spate, un detaliu seducător și rafinat, care pune în valoare linia spatelui fără a pierde din eleganță.',
    rentPrice: 3200,
    price: 4500,
    type: DressType.BUY,
    imageUrl: '/images/daiana_front.jpg',
    images: ['/images/daiana_front.jpg', '/images/daiana_back.jpg', '/images/daiana_side.jpg', '/images/daiana_detail_1.jpg', '/images/daiana_detail_2.jpg'],
    currency: 'RON',
    sizes: ['36', '38'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Satin fin, mătăsos', silhouette: 'Dreaptă / Minimalistă', neckline: 'Subtil rotunjit / V pe spate' }
  },
  {
    id: 'imperial-elia',
    name: 'Elia',
    description: 'Această rochie de mireasă tip sirenă, îmbină eleganța clasică cu senzualitatea modernă într-o siluetă perfect conturată. Partea de jos, realizată din mătase naturală, cade fluid și impecabil, urmărind linia corpului până la genunchi, unde se deschide delicat, oferind rochiei un mers grațios și o prezență spectaculoasă. Bustul este punctul central al creației: tip corset, cu transparențe fine, atent construite pentru a pune în valoare dantela aplicată manual. Jocul subtil dintre transparență și broderia bogată creează impresia de ușurință și rafinament. Un mare avantaj al acestei rochii este versatilitatea ei: se pretează excelent la accesorizare cu trene detașabile.',
    rentPrice: 3300,
    price: 4500,
    type: DressType.BUY,
    imageUrl: '/images/elia_front.jpg',
    images: ['/images/elia_front.jpg', '/images/elia_front_2.jpg', '/images/elia_back.jpg', '/images/elia_side.jpg', '/images/elia_detail.jpg'],
    currency: 'RON',
    sizes: ['38'],
    colors: ['Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mătase naturală, dantelă', silhouette: 'Sirenă', neckline: 'Corset Illusion' }
  },
  {
    id: 'imperial-elise',
    name: 'Elise',
    description: 'Romantism parizian într-o rochie. Elise aduce un aer de haute couture franțuzească cu volane delicate și dantelă cusută manual.',
    rentPrice: 370,
    price: 1300,
    type: DressType.RENT,
    imageUrl: '/images/dress_6_modern.png',
    sizes: ['S', 'M'],
    colors: ['Roz Pal', 'Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Organza & Dantelă', silhouette: 'A-Line', neckline: 'Iluzie' }
  },
  {
    id: 'imperial-ivory-grace',
    name: 'Ivory Grace',
    description: 'Eleganță în cel mai pur alb. Ivory Grace este o declarație de stil clasic, cu o trenă lungă și detalii de perle cusute manual pe corset.',
    rentPrice: 500,
    price: 1800,
    type: DressType.RENT,
    imageUrl: '/images/dress_11_modern.png',
    sizes: ['S', 'M', 'L'],
    colors: ['Ivory', 'Alb Perlat'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Satin Duchesse', silhouette: 'Ballgown', neckline: 'Guler Înalt' }
  },
  {
    id: 'imperial-lumiere',
    name: 'Lumiere',
    description: 'O rochie care captează lumina și o transformă în magie. Lumiere strălucește discret, cu cristale fine integrate în textura materialului.',
    rentPrice: 420,
    price: 1500,
    type: DressType.RENT,
    imageUrl: '/images/dress_12_modern.png',
    sizes: ['XS', 'S', 'M'],
    colors: ['Alb Diamant', 'Champagne'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tulle cu Cristale', silhouette: 'Fit-and-Flare', neckline: 'V-Neck' }
  },
  {
    id: 'imperial-queen',
    name: 'Queen',
    description: 'Concepută pentru momentul suprem. Queen este rochia care transformă fiecare mireasă în regină, cu volum majestuos și detalii de broderie cu fir de aur.',
    rentPrice: 550,
    price: 2000,
    type: DressType.RENT,
    imageUrl: '/images/dress_13_modern.png',
    sizes: ['S', 'M', 'L'],
    colors: ['Alb', 'Auriu'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Mikado & Tulle', silhouette: 'Ballgown', neckline: 'Off-shoulder' }
  },
  {
    id: 'imperial-serena',
    name: 'Serena',
    description: 'Calm, eleganță și fluiditate. Serena este pentru mireasa care dorește o rochie care se mișcă odată cu ea, ușoară ca o adiere de vânt.',
    rentPrice: 320,
    price: 1150,
    type: DressType.RENT,
    imageUrl: '/images/dress_14_modern.png',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Alb', 'Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Chiffon de Mătase', silhouette: 'Dreaptă', neckline: 'Breteluțe' }
  },
  {
    id: 'imperial-mayson',
    name: 'Mayson',
    description: 'Arhitectură vestimentară în alb. Mayson redefinește silueta clasică cu decupaje geometrice subtile și o structură impecabilă.',
    rentPrice: 400,
    price: 1400,
    type: DressType.RENT,
    imageUrl: '/images/dress_15_modern.png',
    sizes: ['S', 'M'],
    colors: ['Alb Mat', 'Ivory'],
    collection: Collection.IMPERIAL,
    details: { fabric: 'Tafta & Crepe', silhouette: 'Asimetric', neckline: 'Un Umăr' }
  }
];
